# -------------------------
#        WORKFLOWS
#
#  When creating a new workflow, make sure to include condition:
#
#  when:
#    and:
#      - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
#      - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
#
#  It's setup this way so we can trigger a release via a POST
#  See limitations: https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2
# -------------------------

workflows:
  version: 2

  analysis:
    when:
      and:
        - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
        - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
    jobs:
      # Run lints on every commit
      - analyze_code

      # Run code checks on PRs
      - analyze_pr
